/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    HelloWorld: typeof import('./src/components/HelloWorld.vue')['default']
    LayoutCrumbs: typeof import('./src/components/private/layoutCrumbs.vue')['default']
    LayoutDetails: typeof import('./src/components/private/layoutDetails.vue')['default']
    LayoutFooter: typeof import('./src/components/private/layoutFooter.vue')['default']
    LayoutHeader: typeof import('./src/components/private/layoutHeader.vue')['default']
    LayoutPage: typeof import('./src/components/private/layoutPage.vue')['default']
    LayoutSearch: typeof import('./src/components/private/layoutSearch.vue')['default']
    LayoutSuspense: typeof import('./src/components/private/layoutSuspense.vue')['default']
    PageLogin: typeof import('./src/components/private/pageLogin.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
}
